config/routes.rb
Rails.application.routes.draw do
  root "events#index"
  resources :events
end

app/models/event.rb
class Event < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def show
    @event = Event.find(params[:id])
  end

  def edit
    @event = Event.find(params[:id])
  end

  def create
    event_params = params.require(:event).permit(
      :description,
      :location,
      :date,
      :capacity,
      :requires_id
    )
    @event = Event.new(event_params)
    @event.save
    redirect_to events_path
  end

  def update
    @event = Event.find(params[:id])
    event_params = params.require(:event).permit(
      :description,
      :location,
      :date,
      :capacity,
      :requires_id
    )
    @event.update(event_params)
    redirect_to events_path
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/edit.html.erb
<h1>Edit Event</h1>

<%= form_for @event do |f| %>

  <p>
    <%= f.label :description %>
    <%= f.text_field :description %>
  </p>

  <p>
    <%= f.label :location %>
    <%= f.text_field :location %>
  </p>

  <p>
    <%= f.label :date %>
    <%= f.date_field :date %>
  </p>

  <p>
    <%= f.label :capacity %>
    <%= f.number_field :capacity %>
  </p>

  <p>
    <label>
      <%= f.check_box :requires_id %>
      Requires ID
    </label>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/events/index.html.erb
<h1>All Events</h1>

<%= link_to "New Event", new_event_path %>

<table>
  <thead>
    <tr>
      <th> Description </th>
      <th> Location </th>
      <th> Capacity </th>
      <th> Date </th>
      <th> Requires ID </th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td>
          <%= link_to event.description, event_path(event) %>
        </td>
        <td>
          <%= event.location %>
        </td>
        <td>
          <%= event.capacity %>
        </td>
        <td>
          <%= event.date %>
        </td>
        <td>
          <%= event.requires_id %>
        </td>
        <td>
          <%= link_to "edit", edit_event_path(event) %> |
          <%= link_to "delete", event_path(event), method: :delete, data: {confirm: "Are you sure?"} %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= form_for @event do |f| %>

  <p>
    <%= f.label :description %>
    <%= f.text_field :description %>
  </p>

  <p>
    <%= f.label :location %>
    <%= f.text_field :location %>
  </p>

  <p>
    <%= f.label :date %>
    <%= f.date_field :date %>
  </p>

  <p>
    <%= f.label :capacity %>
    <%= f.number_field :capacity %>
  </p>

  <p>
    <label>
      <%= f.check_box :requires_id %>
      Requires ID
    </label>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/events/show.html.erb
<p>
  Description:
<%= @event.description %>
</p>

<p>
  Location:
<%= @event.location %>
</p>

<p>
  Capacity:
<%= @event.capacity %>
</p>

<p>
  Date:
<%= @event.date %>
</p>

<p>
  Requires ID:
<%= @event.requires_id %>
</p>


<%= link_to "Show all events", events_path %> |
<%= link_to "Edit", edit_event_path(@event) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsPracticeCrudEvents</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>